### ISSUE TITLE
Possibly incorrect $ROOT path

### ISSUE THREAD

**Issue by command-tab** [trhodeos/modern-n64sdk#2]
Under the **Export the appropriate variables** heading, the docs show `export GCCDIR=$ROOT/GCC`, where `$ROOT` is the value from `$N64_SDK`, which is the place where the extracted 7z SDK resides, all as described.

However, I don't see a `GCC` directory inside `$ROOT`; All I see are `nintendo/` and `ultra/` directories. However, `ultra/` _does_ contain a `GCC` directory. Should the line read `export GCCDIR=$ROOT/ultra/GCC`?

Thank you for scripting and writing all this up! It has been a huge help getting a modern N64 toolchain working on macOS ❤️

**Comment by trhodeos** [comment]
Ah, good catch! Thanks for opening the issue, it should be fixed now. Let me know if you run into other issues!
